-- Phase 7 — Row-Level Security.
--
-- Generated by scripts/generate-rls.mjs. Edit the generator, not this file.
--
-- ADR-002 required tenant isolation in the database rather than in the
-- repository layer. This is that. Every policy below denies by default:
-- app_tenant() returns NULL when the connection has not declared a tenant,
-- and NULL never equals anything, so an un-scoped connection reads nothing.

-- The tenant of the current connection. STABLE so the planner may cache it
-- within a statement; the second argument makes a missing setting return
-- NULL instead of raising, which is what turns "forgot to set it" into
-- "sees nothing" rather than "crashes".
CREATE OR REPLACE FUNCTION app_tenant() RETURNS text
  LANGUAGE sql STABLE AS $$ SELECT current_setting('app.tenant_id', true) $$;

REVOKE ALL ON FUNCTION app_tenant() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION app_tenant() TO kayan_app, kayan_auth, kayan_owner;

-- ── Tenant itself ────────────────────────────────────────
ALTER TABLE "Tenant" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Tenant" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "Tenant";
CREATE POLICY tenant_isolation ON "Tenant" AS PERMISSIVE FOR ALL TO PUBLIC
  USING (id = app_tenant()) WITH CHECK (id = app_tenant());

-- ── Tables that carry tenantId ───────────────────────────
ALTER TABLE "AuditLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AuditLog" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "AuditLog";
CREATE POLICY tenant_isolation ON "AuditLog" AS PERMISSIVE FOR ALL TO PUBLIC
  USING ("tenantId" = app_tenant()) WITH CHECK ("tenantId" = app_tenant());

ALTER TABLE "Category" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Category" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "Category";
CREATE POLICY tenant_isolation ON "Category" AS PERMISSIVE FOR ALL TO PUBLIC
  USING ("tenantId" = app_tenant()) WITH CHECK ("tenantId" = app_tenant());

ALTER TABLE "Color" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Color" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "Color";
CREATE POLICY tenant_isolation ON "Color" AS PERMISSIVE FOR ALL TO PUBLIC
  USING ("tenantId" = app_tenant()) WITH CHECK ("tenantId" = app_tenant());

ALTER TABLE "Company" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Company" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "Company";
CREATE POLICY tenant_isolation ON "Company" AS PERMISSIVE FOR ALL TO PUBLIC
  USING ("tenantId" = app_tenant()) WITH CHECK ("tenantId" = app_tenant());

ALTER TABLE "CostCalculation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CostCalculation" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "CostCalculation";
CREATE POLICY tenant_isolation ON "CostCalculation" AS PERMISSIVE FOR ALL TO PUBLIC
  USING ("tenantId" = app_tenant()) WITH CHECK ("tenantId" = app_tenant());

ALTER TABLE "Customer" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Customer" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "Customer";
CREATE POLICY tenant_isolation ON "Customer" AS PERMISSIVE FOR ALL TO PUBLIC
  USING ("tenantId" = app_tenant()) WITH CHECK ("tenantId" = app_tenant());

ALTER TABLE "DamageRecord" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DamageRecord" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "DamageRecord";
CREATE POLICY tenant_isolation ON "DamageRecord" AS PERMISSIVE FOR ALL TO PUBLIC
  USING ("tenantId" = app_tenant()) WITH CHECK ("tenantId" = app_tenant());

ALTER TABLE "EmbroideryOption" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "EmbroideryOption" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "EmbroideryOption";
CREATE POLICY tenant_isolation ON "EmbroideryOption" AS PERMISSIVE FOR ALL TO PUBLIC
  USING ("tenantId" = app_tenant()) WITH CHECK ("tenantId" = app_tenant());

ALTER TABLE "Formula" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Formula" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "Formula";
CREATE POLICY tenant_isolation ON "Formula" AS PERMISSIVE FOR ALL TO PUBLIC
  USING ("tenantId" = app_tenant()) WITH CHECK ("tenantId" = app_tenant());

ALTER TABLE "Material" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Material" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "Material";
CREATE POLICY tenant_isolation ON "Material" AS PERMISSIVE FOR ALL TO PUBLIC
  USING ("tenantId" = app_tenant()) WITH CHECK ("tenantId" = app_tenant());

ALTER TABLE "Penalty" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Penalty" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "Penalty";
CREATE POLICY tenant_isolation ON "Penalty" AS PERMISSIVE FOR ALL TO PUBLIC
  USING ("tenantId" = app_tenant()) WITH CHECK ("tenantId" = app_tenant());

ALTER TABLE "PrintingOption" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PrintingOption" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "PrintingOption";
CREATE POLICY tenant_isolation ON "PrintingOption" AS PERMISSIVE FOR ALL TO PUBLIC
  USING ("tenantId" = app_tenant()) WITH CHECK ("tenantId" = app_tenant());

ALTER TABLE "Product" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Product" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "Product";
CREATE POLICY tenant_isolation ON "Product" AS PERMISSIVE FOR ALL TO PUBLIC
  USING ("tenantId" = app_tenant()) WITH CHECK ("tenantId" = app_tenant());

ALTER TABLE "ProductionOrder" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProductionOrder" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "ProductionOrder";
CREATE POLICY tenant_isolation ON "ProductionOrder" AS PERMISSIVE FOR ALL TO PUBLIC
  USING ("tenantId" = app_tenant()) WITH CHECK ("tenantId" = app_tenant());

ALTER TABLE "Quotation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Quotation" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "Quotation";
CREATE POLICY tenant_isolation ON "Quotation" AS PERMISSIVE FOR ALL TO PUBLIC
  USING ("tenantId" = app_tenant()) WITH CHECK ("tenantId" = app_tenant());

ALTER TABLE "SalesOrder" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SalesOrder" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "SalesOrder";
CREATE POLICY tenant_isolation ON "SalesOrder" AS PERMISSIVE FOR ALL TO PUBLIC
  USING ("tenantId" = app_tenant()) WITH CHECK ("tenantId" = app_tenant());

ALTER TABLE "SecondaryExpense" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SecondaryExpense" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "SecondaryExpense";
CREATE POLICY tenant_isolation ON "SecondaryExpense" AS PERMISSIVE FOR ALL TO PUBLIC
  USING ("tenantId" = app_tenant()) WITH CHECK ("tenantId" = app_tenant());

ALTER TABLE "Size" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Size" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "Size";
CREATE POLICY tenant_isolation ON "Size" AS PERMISSIVE FOR ALL TO PUBLIC
  USING ("tenantId" = app_tenant()) WITH CHECK ("tenantId" = app_tenant());

ALTER TABLE "StockMovement" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StockMovement" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "StockMovement";
CREATE POLICY tenant_isolation ON "StockMovement" AS PERMISSIVE FOR ALL TO PUBLIC
  USING ("tenantId" = app_tenant()) WITH CHECK ("tenantId" = app_tenant());

ALTER TABLE "Supplier" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Supplier" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "Supplier";
CREATE POLICY tenant_isolation ON "Supplier" AS PERMISSIVE FOR ALL TO PUBLIC
  USING ("tenantId" = app_tenant()) WITH CHECK ("tenantId" = app_tenant());

ALTER TABLE "Supply" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Supply" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "Supply";
CREATE POLICY tenant_isolation ON "Supply" AS PERMISSIVE FOR ALL TO PUBLIC
  USING ("tenantId" = app_tenant()) WITH CHECK ("tenantId" = app_tenant());

ALTER TABLE "SupplyTransaction" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SupplyTransaction" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "SupplyTransaction";
CREATE POLICY tenant_isolation ON "SupplyTransaction" AS PERMISSIVE FOR ALL TO PUBLIC
  USING ("tenantId" = app_tenant()) WITH CHECK ("tenantId" = app_tenant());

ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "User" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "User";
CREATE POLICY tenant_isolation ON "User" AS PERMISSIVE FOR ALL TO PUBLIC
  USING ("tenantId" = app_tenant()) WITH CHECK ("tenantId" = app_tenant());

ALTER TABLE "Warehouse" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Warehouse" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "Warehouse";
CREATE POLICY tenant_isolation ON "Warehouse" AS PERMISSIVE FOR ALL TO PUBLIC
  USING ("tenantId" = app_tenant()) WITH CHECK ("tenantId" = app_tenant());

-- ── Child tables, isolated through their parent ──────────
ALTER TABLE "ProductVariant" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProductVariant" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "ProductVariant";
CREATE POLICY tenant_isolation ON "ProductVariant" AS PERMISSIVE FOR ALL TO PUBLIC
  USING (EXISTS (SELECT 1 FROM "Product" p WHERE p.id = "ProductVariant"."productId" AND p."tenantId" = app_tenant()))
  WITH CHECK (EXISTS (SELECT 1 FROM "Product" p WHERE p.id = "ProductVariant"."productId" AND p."tenantId" = app_tenant()));

ALTER TABLE "ProductImage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProductImage" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "ProductImage";
CREATE POLICY tenant_isolation ON "ProductImage" AS PERMISSIVE FOR ALL TO PUBLIC
  USING (EXISTS (SELECT 1 FROM "Product" p WHERE p.id = "ProductImage"."productId" AND p."tenantId" = app_tenant()))
  WITH CHECK (EXISTS (SELECT 1 FROM "Product" p WHERE p.id = "ProductImage"."productId" AND p."tenantId" = app_tenant()));

ALTER TABLE "ProductMaterial" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProductMaterial" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "ProductMaterial";
CREATE POLICY tenant_isolation ON "ProductMaterial" AS PERMISSIVE FOR ALL TO PUBLIC
  USING (EXISTS (SELECT 1 FROM "Product" p WHERE p.id = "ProductMaterial"."productId" AND p."tenantId" = app_tenant()))
  WITH CHECK (EXISTS (SELECT 1 FROM "Product" p WHERE p.id = "ProductMaterial"."productId" AND p."tenantId" = app_tenant()));

ALTER TABLE "ProductPrintingOption" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProductPrintingOption" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "ProductPrintingOption";
CREATE POLICY tenant_isolation ON "ProductPrintingOption" AS PERMISSIVE FOR ALL TO PUBLIC
  USING (EXISTS (SELECT 1 FROM "Product" p WHERE p.id = "ProductPrintingOption"."productId" AND p."tenantId" = app_tenant()))
  WITH CHECK (EXISTS (SELECT 1 FROM "Product" p WHERE p.id = "ProductPrintingOption"."productId" AND p."tenantId" = app_tenant()));

ALTER TABLE "ProductEmbroideryOption" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProductEmbroideryOption" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "ProductEmbroideryOption";
CREATE POLICY tenant_isolation ON "ProductEmbroideryOption" AS PERMISSIVE FOR ALL TO PUBLIC
  USING (EXISTS (SELECT 1 FROM "Product" p WHERE p.id = "ProductEmbroideryOption"."productId" AND p."tenantId" = app_tenant()))
  WITH CHECK (EXISTS (SELECT 1 FROM "Product" p WHERE p.id = "ProductEmbroideryOption"."productId" AND p."tenantId" = app_tenant()));

ALTER TABLE "ProductFormula" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProductFormula" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "ProductFormula";
CREATE POLICY tenant_isolation ON "ProductFormula" AS PERMISSIVE FOR ALL TO PUBLIC
  USING (EXISTS (SELECT 1 FROM "Product" p WHERE p.id = "ProductFormula"."productId" AND p."tenantId" = app_tenant()))
  WITH CHECK (EXISTS (SELECT 1 FROM "Product" p WHERE p.id = "ProductFormula"."productId" AND p."tenantId" = app_tenant()));

ALTER TABLE "WarehouseLocation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WarehouseLocation" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "WarehouseLocation";
CREATE POLICY tenant_isolation ON "WarehouseLocation" AS PERMISSIVE FOR ALL TO PUBLIC
  USING (EXISTS (SELECT 1 FROM "Warehouse" w WHERE w.id = "WarehouseLocation"."warehouseId" AND w."tenantId" = app_tenant()))
  WITH CHECK (EXISTS (SELECT 1 FROM "Warehouse" w WHERE w.id = "WarehouseLocation"."warehouseId" AND w."tenantId" = app_tenant()));

ALTER TABLE "Stock" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Stock" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "Stock";
CREATE POLICY tenant_isolation ON "Stock" AS PERMISSIVE FOR ALL TO PUBLIC
  USING (EXISTS (SELECT 1 FROM "Warehouse" w WHERE w.id = "Stock"."warehouseId" AND w."tenantId" = app_tenant()))
  WITH CHECK (EXISTS (SELECT 1 FROM "Warehouse" w WHERE w.id = "Stock"."warehouseId" AND w."tenantId" = app_tenant()));

ALTER TABLE "CustomerActivity" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CustomerActivity" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "CustomerActivity";
CREATE POLICY tenant_isolation ON "CustomerActivity" AS PERMISSIVE FOR ALL TO PUBLIC
  USING (EXISTS (SELECT 1 FROM "Customer" c WHERE c.id = "CustomerActivity"."customerId" AND c."tenantId" = app_tenant()))
  WITH CHECK (EXISTS (SELECT 1 FROM "Customer" c WHERE c.id = "CustomerActivity"."customerId" AND c."tenantId" = app_tenant()));

ALTER TABLE "SupplierProduct" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SupplierProduct" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "SupplierProduct";
CREATE POLICY tenant_isolation ON "SupplierProduct" AS PERMISSIVE FOR ALL TO PUBLIC
  USING (EXISTS (SELECT 1 FROM "Supplier" s WHERE s.id = "SupplierProduct"."supplierId" AND s."tenantId" = app_tenant()))
  WITH CHECK (EXISTS (SELECT 1 FROM "Supplier" s WHERE s.id = "SupplierProduct"."supplierId" AND s."tenantId" = app_tenant()));

ALTER TABLE "QuotationLine" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "QuotationLine" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "QuotationLine";
CREATE POLICY tenant_isolation ON "QuotationLine" AS PERMISSIVE FOR ALL TO PUBLIC
  USING (EXISTS (SELECT 1 FROM "Quotation" q WHERE q.id = "QuotationLine"."quotationId" AND q."tenantId" = app_tenant()))
  WITH CHECK (EXISTS (SELECT 1 FROM "Quotation" q WHERE q.id = "QuotationLine"."quotationId" AND q."tenantId" = app_tenant()));

ALTER TABLE "SalesOrderLine" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SalesOrderLine" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "SalesOrderLine";
CREATE POLICY tenant_isolation ON "SalesOrderLine" AS PERMISSIVE FOR ALL TO PUBLIC
  USING (EXISTS (SELECT 1 FROM "SalesOrder" o WHERE o.id = "SalesOrderLine"."salesOrderId" AND o."tenantId" = app_tenant()))
  WITH CHECK (EXISTS (SELECT 1 FROM "SalesOrder" o WHERE o.id = "SalesOrderLine"."salesOrderId" AND o."tenantId" = app_tenant()));

ALTER TABLE "ProductionOrderAssignee" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProductionOrderAssignee" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "ProductionOrderAssignee";
CREATE POLICY tenant_isolation ON "ProductionOrderAssignee" AS PERMISSIVE FOR ALL TO PUBLIC
  USING (EXISTS (SELECT 1 FROM "ProductionOrder" o WHERE o.id = "ProductionOrderAssignee"."productionOrderId" AND o."tenantId" = app_tenant()))
  WITH CHECK (EXISTS (SELECT 1 FROM "ProductionOrder" o WHERE o.id = "ProductionOrderAssignee"."productionOrderId" AND o."tenantId" = app_tenant()));

ALTER TABLE "WorkOrder" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WorkOrder" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "WorkOrder";
CREATE POLICY tenant_isolation ON "WorkOrder" AS PERMISSIVE FOR ALL TO PUBLIC
  USING (EXISTS (SELECT 1 FROM "ProductionOrder" o WHERE o.id = "WorkOrder"."productionOrderId" AND o."tenantId" = app_tenant()))
  WITH CHECK (EXISTS (SELECT 1 FROM "ProductionOrder" o WHERE o.id = "WorkOrder"."productionOrderId" AND o."tenantId" = app_tenant()));

ALTER TABLE "FormulaVersion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FormulaVersion" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "FormulaVersion";
CREATE POLICY tenant_isolation ON "FormulaVersion" AS PERMISSIVE FOR ALL TO PUBLIC
  USING (EXISTS (SELECT 1 FROM "Formula" f WHERE f.id = "FormulaVersion"."formulaId" AND f."tenantId" = app_tenant()))
  WITH CHECK (EXISTS (SELECT 1 FROM "Formula" f WHERE f.id = "FormulaVersion"."formulaId" AND f."tenantId" = app_tenant()));

ALTER TABLE "FormulaLine" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FormulaLine" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "FormulaLine";
CREATE POLICY tenant_isolation ON "FormulaLine" AS PERMISSIVE FOR ALL TO PUBLIC
  USING (EXISTS (SELECT 1 FROM "FormulaVersion" v JOIN "Formula" f ON f.id = v."formulaId" WHERE v.id = "FormulaLine"."formulaVersionId" AND f."tenantId" = app_tenant()))
  WITH CHECK (EXISTS (SELECT 1 FROM "FormulaVersion" v JOIN "Formula" f ON f.id = v."formulaId" WHERE v.id = "FormulaLine"."formulaVersionId" AND f."tenantId" = app_tenant()));

ALTER TABLE "FormulaParam" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FormulaParam" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "FormulaParam";
CREATE POLICY tenant_isolation ON "FormulaParam" AS PERMISSIVE FOR ALL TO PUBLIC
  USING (EXISTS (SELECT 1 FROM "FormulaVersion" v JOIN "Formula" f ON f.id = v."formulaId" WHERE v.id = "FormulaParam"."formulaVersionId" AND f."tenantId" = app_tenant()))
  WITH CHECK (EXISTS (SELECT 1 FROM "FormulaVersion" v JOIN "Formula" f ON f.id = v."formulaId" WHERE v.id = "FormulaParam"."formulaVersionId" AND f."tenantId" = app_tenant()));

ALTER TABLE "CostCalculationFormula" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CostCalculationFormula" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "CostCalculationFormula";
CREATE POLICY tenant_isolation ON "CostCalculationFormula" AS PERMISSIVE FOR ALL TO PUBLIC
  USING (EXISTS (SELECT 1 FROM "CostCalculation" c WHERE c.id = "CostCalculationFormula"."costCalculationId" AND c."tenantId" = app_tenant()))
  WITH CHECK (EXISTS (SELECT 1 FROM "CostCalculation" c WHERE c.id = "CostCalculationFormula"."costCalculationId" AND c."tenantId" = app_tenant()));

ALTER TABLE "CostCalculationLine" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CostCalculationLine" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "CostCalculationLine";
CREATE POLICY tenant_isolation ON "CostCalculationLine" AS PERMISSIVE FOR ALL TO PUBLIC
  USING (EXISTS (SELECT 1 FROM "CostCalculation" c WHERE c.id = "CostCalculationLine"."costCalculationId" AND c."tenantId" = app_tenant()))
  WITH CHECK (EXISTS (SELECT 1 FROM "CostCalculation" c WHERE c.id = "CostCalculationLine"."costCalculationId" AND c."tenantId" = app_tenant()));

ALTER TABLE "PenaltyEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PenaltyEvent" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "PenaltyEvent";
CREATE POLICY tenant_isolation ON "PenaltyEvent" AS PERMISSIVE FOR ALL TO PUBLIC
  USING (EXISTS (SELECT 1 FROM "Penalty" p WHERE p.id = "PenaltyEvent"."penaltyId" AND p."tenantId" = app_tenant()))
  WITH CHECK (EXISTS (SELECT 1 FROM "Penalty" p WHERE p.id = "PenaltyEvent"."penaltyId" AND p."tenantId" = app_tenant()));

ALTER TABLE "Session" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Session" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "Session";
CREATE POLICY tenant_isolation ON "Session" AS PERMISSIVE FOR ALL TO PUBLIC
  USING (EXISTS (SELECT 1 FROM "User" u WHERE u.id = "Session"."userId" AND u."tenantId" = app_tenant()))
  WITH CHECK (EXISTS (SELECT 1 FROM "User" u WHERE u.id = "Session"."userId" AND u."tenantId" = app_tenant()));

ALTER TABLE "Attachment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Attachment" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "Attachment";
CREATE POLICY tenant_isolation ON "Attachment" AS PERMISSIVE FOR ALL TO PUBLIC
  USING ((
       EXISTS (SELECT 1 FROM "Customer" c         WHERE c.id = "Attachment"."customerId"   AND c."tenantId" = app_tenant())
    OR EXISTS (SELECT 1 FROM "Supplier" s         WHERE s.id = "Attachment"."supplierId"   AND s."tenantId" = app_tenant())
    OR EXISTS (SELECT 1 FROM "Quotation" q        WHERE q.id = "Attachment"."quotationId"  AND q."tenantId" = app_tenant())
    OR EXISTS (SELECT 1 FROM "SalesOrder" o       WHERE o.id = "Attachment"."salesOrderId" AND o."tenantId" = app_tenant())
    OR EXISTS (SELECT 1 FROM "SecondaryExpense" e WHERE e.id = "Attachment"."expenseId"    AND e."tenantId" = app_tenant())
    OR EXISTS (SELECT 1 FROM "DamageRecord" d     WHERE d.id = "Attachment"."damageId"     AND d."tenantId" = app_tenant())
  ))
  WITH CHECK ((
       EXISTS (SELECT 1 FROM "Customer" c         WHERE c.id = "Attachment"."customerId"   AND c."tenantId" = app_tenant())
    OR EXISTS (SELECT 1 FROM "Supplier" s         WHERE s.id = "Attachment"."supplierId"   AND s."tenantId" = app_tenant())
    OR EXISTS (SELECT 1 FROM "Quotation" q        WHERE q.id = "Attachment"."quotationId"  AND q."tenantId" = app_tenant())
    OR EXISTS (SELECT 1 FROM "SalesOrder" o       WHERE o.id = "Attachment"."salesOrderId" AND o."tenantId" = app_tenant())
    OR EXISTS (SELECT 1 FROM "SecondaryExpense" e WHERE e.id = "Attachment"."expenseId"    AND e."tenantId" = app_tenant())
    OR EXISTS (SELECT 1 FROM "DamageRecord" d     WHERE d.id = "Attachment"."damageId"     AND d."tenantId" = app_tenant())
  ));

-- ── Deliberately global (no RLS) ─────────────────────────
-- Role: the role catalogue is identical for every tenant
-- Permission: the permission catalogue is identical for every tenant
-- RolePermission: the permission matrix is global configuration, seeded from code
-- _prisma_migrations: migration history, owner-only; the app role is never granted it

-- ── Privileges ───────────────────────────────────────────
-- The application role owns nothing and may not create anything. Its
-- entire visibility is decided by the policies above.
GRANT USAGE ON SCHEMA public TO kayan_app, kayan_auth;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO kayan_app, kayan_auth;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO kayan_app, kayan_auth;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO kayan_app, kayan_auth;

-- Migration history is owner business only.
REVOKE ALL ON TABLE "_prisma_migrations" FROM kayan_app, kayan_auth;
